<?php require_once('views/helpers/Location.php');?>
<form id="addLocationForm"  action="<?php echo $this->base_url;?>/training/location-add/outputType/json" method="POST" <?php if($this->viewonly) echo 'disabled="disabled"'; ?>>

  <div class="fieldLabelThin" id="training_location_name_lbl"><span class="required">*</span><?php tp('Location name');?></div>
  <div class="fieldInput" >
    <input type="text" size="70" name="training_location_name" id="locationName" value="<?php if(isset($this->rowLocation)) echo $this->rowLocation['training_location_name']; ?>" <?php echo $this->viewonly; ?>>
  </div>

  <div class="fieldLabelThin" id="location_province_id_lbl"><span class="required">*</span><?php echo (@$this->translation['Region A (Province)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 1, 'location_province_id', @$this->rowLocation['province_id'], ($this->setting['display_region_b']?'location_district_id':false));?></div>
  <?php 
  if ( $this->setting['display_region_b'] ) { ?>
  <div class="fieldLabelThin" id="district_id_lbl"><span class="required">*</span><?php echo (@$this->translation['Region B (Health District)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 2, 'location_district_id', @$this->rowLocation['district_id'], ($this->setting['display_region_c']?'location_region_c_id':false));?></div>
  <?php } ?>
  <?php if ( $this->setting['display_region_c'] ) { ?>
  <div class="fieldLabelThin" id="region_c_id_lbl"><span class="required">*</span><?php echo (@$this->translation['Region C (Local Region)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 3, 'location_region_c_id', @$this->rowLocation['region_c_id'], false);?></div>
  <?php } ?>

  <div class="fieldLabelThin" id="location_city_lbl"><?php echo (@$this->translation['City or Town']); ?></div><div id="cityAutoComplete">
      <div class="fieldInput"><input name="location_city" id="location_city" type="text" size="40" maxlength="128" value="<?php echo $this->rowLocation['city_name'];?>" /><input style="margin-left:10px;" type="checkbox" id="is_new_city" name="is_new_city" value="is_new_city" /><label class="label"><?php tp('New city'); ?></label><div class="clear"></div>
      <div id="cityContainer"  class="autocomplete"></div></div>
  </div>
  <?php renderCityAutocomplete('location','cityContainer',$this->base_url.'/facility/cityList/outputType/text/',$this->setting['num_location_tiers']);?>


</form>

<div class="clear"></div>