<?php


if (($this->hasACL('pre_service')) || ($this->hasACL('admin_preservice'))){
$navAdmin = array( // directory => array of pages (index for root)
	'country' => array( // file => label
		'index'				=> t('Country Setup'),
		'settings'			=> t('Country Setup'),
		'region'			=> t('Region Setup'),
		'region-move'		=> t('Move Regions'),
),
	'training' => array(
		'index'				=> t('Training'),
	'settings'				=> t('Training Settings'),
		'category'			=> t('Training Category'),
		'assign-title'		=> t('Assign Titles'),
		'title'				=> t('Training Title'),
		'organizer' 		=> t('Training Organizer'),
		'level'				=> t('Training Level'),
		'topic'				=> t('Training Topic'),
		'pepfar'			=> t('PEPFAR Category'),
		'funding'			=> t('Funding'),
		'recommend'			=> t('Recommended Topic'),
		'gotcurriculum'		=> t('Nat. Curriculum'),
		'method'			=> t('Training Method'),
	),
	'people' => array(
		'index'				=> t('People'),
		'settings'			=> t('People Settings'),
		'qual'				=> t('Qualifications'),
		'responsibility'	=> t('Responsibility'),
		'types'				=> t('Trainer Types'),
		'skills'			=> t('Trainer Skills'),
		'languages'			=> t('Languages'),
		'affiliations'		=> t('Affiliations'),
		'title'				=> t('Titles'),
		'suffix'			=> t('Suffix'),
		'active-trainer'	=> t('Active Trainer'),
 	),
	'facilities' => array(
		'index'				=> t('Facilities'),
		'settings'			=> t('Facilities Settings'),
		'types'				=> t('Facility Types'),
		'sponsors'			=> t('Facility Sponsors'),
	),
	'preservice' => array(
		'index'				=> t('Preservice'),
		'classes'			=> t('Classes'),
		'cadres'			=> t('Cadres'),
		'degrees'			=> t('Degrees'),
		'funding'			=> t('Funding'),
		'institutiontypes'	=> t('Institution types'),
		'languages'			=> t('Languages'),
		'nationalities'		=> t('Nationalities'),
		'joindropreasons'	=> t('Join & drop reasons'),
		'sponsors'			=> t('Sponsors'),
		//'studenttypes'		=> t('Student types'),
		'tutortypes'		=> t('Tutor types'),
		'coursetypes'		=> t('Course types'),
		'religion'			=> t('Religious denominations'),
	),
	'users' => array(
		'index'				=> t('Users'),
		'add'				=> t('Add Users'),
	),
);



} else {
$navAdmin = array( // directory => array of pages (index for root)
	'country' => array( // file => label
		'index'				=> t('Country Setup'),
		'settings'			=> t('Country Setup'),
		'region'			=> t('Region Setup'),
		'region-move'		=> t('Move Regions'),
),
	'training' => array(
		'index'				=> t('Training'),
	'settings'				=> t('Training Settings'),
		'category'			=> t('Training Category'),
		'assign-title'		=> t('Assign Titles'),
		'title'				=> t('Training Title'),
		'organizer' 		=> t('Training Organizer'),
		'level'				=> t('Training Level'),
		'topic'				=> t('Training Topic'),
		'pepfar'			=> t('PEPFAR Category'),
		'funding'			=> t('Funding'),
		'recommend'			=> t('Recommended Topic'),
		'gotcurriculum'		=> t('Nat. Curriculum'),
		'method'			=> t('Training Method'),
	),
	'people' => array(
		'index'				=> t('People'),
		'settings'			=> t('People Settings'),
		'qual'				=> t('Qualifications'),
		'responsibility'	=> t('Responsibility'),
		'types'				=> t('Trainer Types'),
		'skills'			=> t('Trainer Skills'),
		'languages'			=> t('Languages'),
		'affiliations'		=> t('Affiliations'),
		'title'				=> t('Titles'),
		'suffix'			=> t('Suffix'),
		'active-trainer'	=> t('Active Trainer'),
 	),
	'facilities' => array(
		'index'				=> t('Facilities'),
		'settings'			=> t('Facilities Settings'),
		'types'				=> t('Facility Types'),
		'sponsors'			=> t('Facility Sponsors'),
	),
	'users' => array(
		'index'				=> t('Users'),
		'add'				=> t('Add Users'),
	),
);



}

?>


<!-- left nav admin navigation -->
<?php


// Note: $path defined in header.phtml

// Get page title and next page
$parsed_url = parse_url(Settings::$COUNTRY_BASE_URL);
$pathFront = @$parsed_url['path'];
if ( $pathFront )
	$path = str_replace($pathFront,'',$_SERVER['REQUEST_URI']);
else
	$path = $_SERVER['REQUEST_URI'];
$path = $_SERVER['REQUEST_URI'];

// Strip off URL params if any (will be when debugging in Eclipse)
//$qmarkpos = strpos($path, "?");
//if ($qmarkpos != false) {
//	$path = substr($path, 0, $qmarkpos);
//}

$path = explode('/',$path);

//$path = $_SERVER['REQUEST_URI'];
$page = explode('-',$path[2]);
$page[1] = implode('-', array_slice($page,1)); // allow hyphens



//$page = 'assign-title';
$pageTitle = "";
$nextUri = "";
if(isset($page[1]) && isset($navAdmin[$page[0]][$page[1]])) {
	$pageTitle = $navAdmin[$page[0]][$page[1]];

	// get next array element
	foreach($navAdmin as $dir => $navRay) {
		foreach($navRay as $key => $val) {

			if($dir == $page[0] && $key == $page[1]) {
				$next = next($navRay);
				$rayDir = $dir;
				if(!$next) { // end of array, get next array
					$navRay = current($navAdmin);
					$rayDir = key($navAdmin);
					$next = next($navRay); // skip first element (index)

				}
				$nextUri = $rayDir."-".key($navRay);
				break;
			}
			next($navRay);
		}

	}
}
	$sections = array();
	$labels = array();

// generate admin navigation
foreach($navAdmin as $dir => $navRay) {
	
	
	foreach($navRay as $file => $label) {

		if($dir == 'index' || $file == 'index') {
			$uri = false;
		} else {
			$uri = "$dir-$file";
		}
		
		if ( !isset($sections[$dir]) ) $sections[$dir] = array();
		
		if($uri) {
			$isActive = ($path[2] == $uri) ? ' class="active"' : '';
			$sections[$dir][] =	'<li'.$isActive.'><a href="'.($this->base_url).'/admin/'.$uri.'" '.$isActive.'>'.$label."</a>".'</li>';
		} else {
			$labels[$dir] =	$label;
		}
 
	}

}

	echo '<ul>';
	foreach($sections as $dir => $s) {
		echo '<li>'.$labels[$dir]."\n".'<ul>'.implode("\n", $s).'</ul>'."\n".'</li>';
	}
	echo '</ul>';


?>