<?php

// template for page that contains an EditTable

// need $pageTitle and $nextUri variables from these includes

ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean();

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean();

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name']; ?> | <?php echo $pageTitle; ?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
</head>
<body  class="yui-skin-sam">
<div id="pageHolder">
  <div id="header"><?php echo $header; ?></div>
  <div id="content" class="adminDiv">


    <div id="navAdmin"><?php echo $nav;?></div>

    <div id="contentAdmin">
    <h1><?php echo $pageTitle; ?></h1>
	  
	  <fieldset class="settings"><legend>Appearance</legend>
	  <div class="fieldLabel">Application Name</div>
<script type="text/javascript">
function update_app_name(newval) {
	var app_name = YAHOO.util.Dom.get('label_application_name');
	app_name.value = newval;
}
function  confirmRegionDelete(control) {
	  if ( confirm("Are you sure you want to remove this region level? All locations in this level will be erased.") ) {
		  window.location = "<?php echo Settings::$COUNTRY_BASE_URL; ?>/admin/delete-region";  
		}
}
function  confirmRegionAddTop(control) {
    if ( confirm("Are you sure you want to add a region level? A new default location will be created at this level, and all child locations will be added to this default.") ) {
      window.location = "<?php echo Settings::$COUNTRY_BASE_URL; ?>/admin/add-region-top";  
    }
}
function  confirmRegionAddBottom(control) {
    if ( confirm("Are you sure you want to add a region level? A new default location will be created at this level, and all child locations will be added to this default.") ) {
      window.location = "<?php echo Settings::$COUNTRY_BASE_URL; ?>/admin/add-region-bottom";  
    }
}
</script>
	  <div class="fieldInput"><input type="text" name="application_name_clone" value="<?php echo $this->translation['Application Name'];?>" onchange="return update_app_name(this.value);"></input>
	  </div><br/>
	  <?php if (isset($this->setting['logo_id']))   { ?>
	  <img id="logo_img" src="<?php echo Settings::$COUNTRY_BASE_URL.'/file/download/id/'.$this->setting['logo_id'];?>" />
		
	  <?php } ?>
	  <div class="fieldLabel">Logo</div>
	  <div class="fieldInput">
<?php 
    require_once 'views/helpers/FileUpload.php';
    echo FileUpload::displayUploadForm('_system', 0, array('jpg','gif','png'),false);
?>
	  Approximate image dimensions 120x120
	
	   </div>
	   <div class="fieldInput" style="font-size:80%; padding: .5em;">(Refresh this page, or go to the home page to see changes applied.)</div>
	  </fieldset>
<script type="text/javascript">
YAHOO.util.Event.on(window, 'load', initSettingsUploadButton);
</script>
    <fieldset class="settings"><legend>Settings</legend>
    <br/>

     <form method="post" name="adminForm">
    <input type="hidden" name="label_application_name" id="label_application_name" value="<?php echo $this->translation['Application Name'];?>" />
    <table class="settings">
    <thead>
    <tr><th>Field</th><th>Actions</th><th>Label</th><th>Options</th></tr>
    </thead>
    <tr><td class="fieldTitle">Country</td><td></td><td><input type="text" name="country" value="<?php echo $this->country; ?>"></td><td></td></tr>
    <?php if ( $this->setting['num_location_tiers'] < 4) {?>
    <tr><td class="fieldTitle"></td><td><a href="#" onclick="return confirmRegionAddTop();" >Add region</a></td><td></td><td></td>
    <?php }?>
    <tr><td class="fieldTitle">Region A</td><td></td><td><input type="text" name="label_regiona" value="<?php echo $this->label_regiona; ?>"></td><td><a href="<?php echo $this->base_url;?>/admin/country-region/tier/1" onclick="return submitAdminForm(this);">Add/Edit</a></td>
    <?php if($this->setting['display_region_b'] )  { ?>
    
    <tr><td class="fieldTitle">Region B</td><td><?php  if (!$this->setting['display_region_c'] ) {?><a href="#" onclick="return confirmRegionDelete();" >Delete region</a><?php }?></td><td><input type="text" name="label_regionb" value="<?php echo $this->label_regionb; ?>"></td><td><a href="<?php echo $this->base_url;?>/admin/country-region/tier/2" onclick="return submitAdminForm(this);">Add/Edit</a></td>
    <?php } else { ?>
    <tr><td class="fieldTitle"></td><td><?php if ( $this->setting['num_location_tiers'] == 2) {?><a href="#" onclick="return confirmRegionAddBottom();" >Add region</a><?php }?></td><td></td><td></td>
    <?php }?>
    
    <?php if($this->setting['display_region_c'] )  { ?>
    <tr><td class="fieldTitle">Region C</td><td><a href="#" onclick="return confirmRegionDelete();">Delete region</a></td><td><input type="text" name="label_regionc" value="<?php echo $this->label_regionc; ?>"></td><td><a href="<?php echo $this->base_url;?>/admin/country-region/tier/3" onclick="return submitAdminForm(this);">Add/Edit</a></td>
   <?php } else if ($this->setting['display_region_b']) { ?>
    <tr><td class="fieldTitle"></td><td><a href="#" onclick="return confirmRegionAddBottom();" >Add region</a></td><td></td><td></td>
    <?php }?>
  
   <tr><td class="fieldTitle">City/Town</td><td></td><td><input type="text" name="label_citytown" value="<?php echo $this->label_citytown; ?>"></td><td></td>
    </table>





</fieldset>

 <fieldset class="settings"><legend>Modules</legend><br/>
 <div class="fieldInput"><div class="fieldLabel">Evaluation</div>
        <input type="checkbox" name="check_mod_eval" <?php if($this->check_mod_eval) echo 'checked'; ?> id="check_mod_eval"><label for="check_mod_eval">Enable</label>
      </div>
<div class="fieldInput"><div class="fieldLabel">Approvals</div>
        <input type="checkbox" name="check_mod_approvals" <?php if($this->check_mod_approvals) echo 'checked'; ?> id="check_mod_approvals"><label for="check_mod_approvals">Enable</label>
      </div>
<div class="fieldInput"><div class="fieldLabel">Change History</div>
        <input type="checkbox" name="check_mod_historical" <?php if($this->check_mod_historical) echo 'checked'; ?> id="check_mod_historical"><label for="check_mod_historical">Enable</label>
      </div>
<div class="fieldInput"><div class="fieldLabel">Unknown Participants</div>
        <input type="checkbox" name="check_mod_unknown" <?php if($this->check_mod_unknown) echo 'checked'; ?> id="check_mod_unknown"><label for="check_mod_unknown">Enable</label>
      </div>
<div class="fieldInput"><div class="fieldLabel">Training Organizer Partners</div>
        <input type="checkbox" name="display_training_partner" <?php if($this->display_training_partner == 1) echo 'checked'; ?>><label for="display_training_partner">Enable</label>
      </div>
 </fieldset>

  <fieldset class="settings"><legend>Languages</legend><br/>

    <?php foreach($this->languages as $key => $label) { ?>
      <div class="fieldLabel"><?php print $label; ?></div>
      <div class="fieldInput">
        <input type="checkbox" name="locales[]" value="<?php echo $key; ?>" id="<?php echo $key;?>"<?php if(in_array($key, $this->locale_enabled) || $key == $this->locale) print 'checked'; ?>><label for="<?php echo $key;?>">Enable</label>
        &nbsp;
        <input type="radio" name="locale_default" value="<?php echo $key; ?>" id="d<?php echo $key;?>" <?php if($this->locale == $key) print 'checked'; ?>><label for="d<?php echo $key;?>">Default</label>
      </div>

    <?php } ?>

   </fieldset>
    <br/>  


    <input type="hidden" name="redirect" value="<?php echo Settings::$COUNTRY_BASE_URL . '/admin/' . $nextUri; ?>">
    <input type="submit" value="Save & Continue" class="submitArrow">
    <input type="submit" value="Save" name="saveonly" class="submitNoArrow" style="margin-right:1em;">
    </form>


    </div>

    <div class="clear"></div>

	</div>
<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>

</body>
</html>