<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> Training Calendar</title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

</head>
<body class="yui-skin-sam">

<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php print t('Training Calendar');?></h1>

  <div class="hideFromPrint" style="font-weight:bold; margin-bottom:1em; ">
    <a href="#" onclick="window.print(); return false; "><?php tp('Print Calendar');?></a>
  </div>

  <?php print $this->calendar; ?>


  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div>

</body>
</html>