<?php require_once('views/helpers/Location.php');?>
<div class="fieldLabelThin" id="facility_name_lbl"><span class="required">*</span><?php tp('Facility');?></div>
	<div class="fieldInput"><input type="text" name="facility_name"  id="facility_name" value="" size="40" maxlength="40"/></div>

	<div class="fieldLabelThin" id="facility_address1_lbl"><?php tp('Address 1');?></div>
	  <div class="fieldInput"><input type="text" name="facility_address1" id="facility_address1" value="" size="40" maxlength="40"/></div>
	<div class="fieldLabelThin" id="facility_address2_lbl"><?php tp('Address 2');?></div>
	  <div class="fieldInput"><input type="text" name="facility_address2" id="facility_address2" value="" size="40" maxlength="40"/></div>
  
  <div class="fieldLabelThin" id="facility_province_id_lbl"><span class="required">*</span><?php echo (@$this->translation['Region A (Province)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 1, 'facility_province_id', false, 'facility_district_id');?></div>

  <?php if ($this->setting['display_region_b'] ) { ?>
    <div class="fieldLabelThin" id="facility_district_id_lbl"><span class="required">*</span><?php echo (@$this->translation['Region B (Health District)']); ?></div>
    <div class="fieldInput"><?php renderFilter($this->locations, 2, 'facility_district_id', false, ($this->setting['display_region_c']?'facility_region_c_id':false));?></div>
  <?php } ?>
  <?php if ($this->setting['display_region_c'] ) { ?>
    <div class="fieldLabelThin" id="facility_region_c_id_lbl"><span class="required">*</span><?php echo (@$this->translation['Region C (Local Region)']); ?></div>
    <div class="fieldInput"><?php renderFilter($this->locations, 3, 'facility_region_c_id', false, false);?></div>
  <?php } ?>
  <div class="fieldLabelThin" id="facility_city_lbl"><?php echo (@$this->translation['City or Town']); ?></div><div id="cityAutoComplete">
      <div class="fieldInput"><input name="facility_city" id="facility_city" type="text" size="40" maxlength="128" value="" /><input style="margin-left:10px;" type="checkbox" id="is_new_city" name="is_new_city" value="is_new_city" /><label class="label"><?php tp('New city'); ?></label><div class="clear"></div>
      <div id="facilityCityContainer"  class="autocomplete"></div></div>

  	</div>
<?php renderCityAutocomplete('facility','facilityCityContainer',$this->base_url.'/facility/cityList/outputType/text/', $this->setting['num_location_tiers']);?>
	
	
	<div class="fieldLabelThin" id="facility_postal_code_lbl"><?php tp('Postal code');?></div>
	  <div class="fieldInput"><input type="text" name="facility_postal_code" id="facility_postal_code" value="" size="40" maxlength="40"/></div>
	<div class="fieldLabelThin" id="facility_phone_lbl"><?php tp('Phone'); ?></div>
	  <div class="fieldInput"><input type="text" name="facility_phone" id="facility_phone" value="" size="40" maxlength="40"/></div>
	<div class="fieldLabelThin" id="facility_fax_lbl"><?php tp('Fax');?></div>
	  <div class="fieldInput"><input type="text" name="facility_fax" id="facility_fax" value="" size="40" maxlength="40"/></div>
	<div class="fieldLabelThin" id="facility_type_id_lbl"><span class="required">*</span><?php tp('Facility type');?></div>
	<div class="fieldInput"><select id="facility_type_id" name="facility_type_id">
		<option value="">--<?php tp('choose');?>--</option>
		<?php
			foreach ( $this->facility_types as $vals ) {
				echo '<option value="'.$vals['id'].'" >'.$vals['facility_type_phrase'].'</option>';
		}
		?>
	</select></div>
	<div class="fieldLabelThin" id="facility_sponsor_id_lbl"><?php tp('Facility sponsor');?></div>
	<div class="fieldInput">
	<select id="facility_sponsor_id" name="facility_sponsor_id">
		<option value="">--<?php tp('choose');?>--</option>
		<?php
		  if ( @$this->facility_sponsors ) {
					foreach ( $this->facility_sponsors as $vals ) {
						echo '<option value="'.$vals['id'].'" >'.$vals['facility_sponsor_phrase'].'</option>';
				}
		  }
		?>
	</select></div>
	<div class="fieldLabelThin" id="facility_comments_lbl"><?php tp('Comments');?></div>
	<div class="fieldInput"><textarea name="facility_comments" id="facility_comments" cols="40" rows="5" ></textarea></div>



<?php if ( $this->setting['display_region_b'] ) { ?>
  <script>
    filterSubTypeOptions('facility_province_id','facility_district_id'); 
  </script>
<?php } ?>