<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Edit Facility');?></title>
<?php
require_once('views/helpers/Location.php');
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

</head>
<body class="yui-skin-sam" >
<div id="pageHolder">
  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

		<h1><?php tp('Edit Facility');?></h1>


<div class="fieldLabel" id="facility_name_lbl"><?php tp('Facility');?></div>
	<form id="change" action="<?php echo $this->base_url;?>/facility/edit" method="GET">
	<div class="fieldInput"><select name="id"  id="id" onchange="if(this.value != '') this.form.submit();">
	<option value="">-- <?php tp('choose');?> --</option>
	<?php foreach ( $this->facilities as $facility) {
		echo '<option value="'.($facility['id']).'" '.((@$this->facility['id']) == $facility['id']? 'SELECTED':'').' >'.($facility['facility_name']).'</option>';
	}
	?>
	}
	</select>
	</div>
	</form>

	<form id="edit" action="" method="POST">
	<div class="fieldLabel" id="facility_name_lbl"><?php tp('Facility name');?></div>
	<div class="fieldInput"><input type="text" name="facility_name"  id="facility_name" value="<?php echo $this->facility['facility_name'];?>" size="40" maxlength="40"/></div>
	<input type="hidden" name="id" value="<?php echo $this->facility['id'];?>"></input>
	<div class="fieldLabel" id="facility_address1_lbl"><?php tp('Address ');?></div>
	  <div class="fieldInput"><input type="text" name="facility_address1" id="facility_address1" value="<?php echo $this->facility['address_1'];?>" size="40" maxlength="40"/></div>
	<div class="fieldLabel" id="facility_address2_lbl"><?php tp('Address 2');?></div>
	  <div class="fieldInput"><input type="text" name="facility_address2" id="facility_address2" value="<?php echo $this->facility['address_2'];?>" size="40" maxlength="40"/></div>

	<div class="fieldLabel" id="facility_province_id_lbl"><span class="required">*</span><?php echo (@$this->translation['Region A (Province)']); ?></div>
	<div class="fieldInput"><?php renderFilter($this->locations, 1, 'facility_province_id', @$this->facility['province_id'], 'facility_district_id');?></div>
  <?php if ( $this->setting['display_region_b'] ) { ?>
  <div class="fieldLabel" id="district_id_lbl"><span class="required">*</span><?php echo (@$this->translation['Region B (Health District)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 2, 'facility_district_id', @$this->facility['district_id'], ($this->setting['display_region_c']?'facility_region_c_id':false));?></div>
  <?php } ?>
  <?php if ( $this->setting['display_region_c'] ) { ?>
  <div class="fieldLabel" id="region_c_id_lbl"><span class="required">*</span><?php echo (@$this->translation['Region C (Local Region)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 3, 'facility_region_c_id', @$this->facility['region_c_id'], false);?></div>
  <?php } ?>

	<div class="fieldLabel" id="facility_city_lbl"><?php echo (@$this->translation['City or Town']); ?></div><div id="cityAutoComplete">
	    <div class="fieldInput"><input name="facility_city" id="facility_city" type="text" size="40" maxlength="128" value="<?php echo $this->facility['facility_city'];?>" /><input style="margin-left:10px;" type="checkbox" id="is_new_city" name="is_new_city" value="is_new_city" /><label class="label"><?php tp('New city'); ?></label><div class="clear"></div>
	    <div id="cityContainer"  class="autocomplete"></div></div>
	</div>
	<?php renderCityAutocomplete('facility','cityContainer',$this->base_url.'/facility/cityList/outputType/text/',$this->setting['num_location_tiers']);?>

	<div class="fieldLabel" id="facility_postal_code_lbl"><?php tp('Postal code');?></div>
	  <div class="fieldInput"><input type="text" name="facility_postal_code" id="facility_postal_code" value="<?php echo $this->facility['postal_code'];?>" size="40" maxlength="40"/></div>
	<div class="fieldLabel" id="facility_phone_lbl"><?php tp('Phone');?></div>
	  <div class="fieldInput"><input type="text" name="facility_phone" id="facility_phone" value="<?php echo $this->facility['phone'];?>" size="40" maxlength="40"/></div>
	<div class="fieldLabel" id="facility_fax_lbl"><?php tp('Fax');?></div>
	  <div class="fieldInput"><input type="text" name="facility_fax" id="facility_fax" value="<?php echo $this->facility['fax'];?>" size="40" maxlength="40"/></div>
	<div class="fieldLabel" id="facility_type_id_lbl"><span class="required">*</span><?php tp('Facility type');?></div>
	<div class="fieldInput"><select id="facility_type_id" name="facility_type_id">
		<option value="">--<?php tp('choose');?>--</option>
		<?php
			foreach ( $this->facility_types as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->facility['type_option_id']) == $vals['id']? 'SELECTED':'').' >'.$vals['facility_type_phrase'].'</option>';
		}
		?>
	</select></div>
	<div class="fieldLabel" id="facility_sponsor_id_lbl"><?php tp('Facility sponsor');?></div>
	<div class="fieldInput">
	<select id="facility_sponsor_id" name="facility_sponsor_id">
		<option value="">--<?php tp('choose');?>--</option>
		<?php
			foreach ( $this->facility_sponsors as $vals ) {
				echo '<option value="'.$vals['id'].'"  '.((@$this->facility['sponsor_option_id']) == $vals['id']? 'SELECTED':'').' >'.$vals['facility_sponsor_phrase'].'</option>';
		}
		?>
	</select></div>
	<div class="fieldLabel" id="facility_comments_lbl"><?php tp('Facility Comments');?></div>
	<div class="fieldInput"><textarea name="facility_comments" id="facility_comments" size="40" maxlength="40" ><?php echo $this->facility['facility_comments'];?></textarea></div>


<div class="clear" ></div>
		<button type="button" id="submitFacility" class="submitNoArrow"><?php tp('Save changes');?></button>
    	<div style="float:right;">&nbsp;</div><?php if ($this->okToDelete) { ?><input type="button" id="deleteFacility" name="deleteFacility" value="Delete" class="submitNoArrow"  onclick="doDelete();" /><?php } ?>
		<script type="text/javascript">
			addAjaxSubmit('submitFacility','edit','<?php echo $this->base_url;?>/facility/edit/outputType/json');
		</script>
		</form>
		<div class="clear" ></div>
  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>

<script language="JavaScript">
function doDelete() {
	if(confirm("<?php tp('Are you sure you wish to delete this facility?');?>")) {
		window.location = '<?php echo $this->base_url;?>/facility/delete/id/<?php echo $this->facility['id'];?>';
		return false;
	}
}
</script>

</body>
</html>

