<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> Training Calendar</title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

</head>
<body class="yui-skin-sam">

<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php print t('Training Calendar');?></h1>

  <div class="calenderLinks hideFromPrint" style="font-weight:bold; float:left; ">
    <a href="#" onclick="window.print(); return false; "><?php tp('Print Calendar');?></a> <br/>
    <a href="#" onclick="return showControls();"><?php tp("Add trainings"); ?></a> <br/>
    <?php echo t('Training'.space.'Reports'); ?> <a href="<?php echo $this->base_url; ?>/reports/trainings?showProvince=on&showDistrict=on&showCategory=on&showTrainingTitle=on&showLocation=on&showOrganizer=on&end-day=<?php echo date('d'); ?>&end-month=<?php echo date('m'); ?>&end-year=<?php echo date('Y'); ?>&limit=1&go=Preview"><?php  tp('Past');   ?></a> <a href="<?php echo $this->base_url; ?>/reports/trainings?showProvince=on&showDistrict=on&showCategory=on&showTrainingTitle=on&showLocation=on&showOrganizer=on&end-day=31&end-month=12&end-year=2099&start-day=<?php echo date('d'); ?>&start-month=<?php echo date('m'); ?>&start-year=<?php echo date('Y'); ?>&limit=1&go=Preview"><?php  tp('Future'); ?></a>
  </div>

  <div class="hideFromPrint right" style="max-width:200px;padding:0 20px; margin-bottom:1em;">
  	<span style="font-weight:bold;clear:right;"><?php tp('Legend'); ?></span> <br/>
  	<span class="block trainOld width100"> <?php echo t('Future').space.t('Training'); ?> </span>
  	<span class="block trainNew width100"> <?php echo t('Past').space.t('Training'); ?>   </span>
  	<span class="red"><?php tp('Today'); ?></span>
  </div>

  <?php print $this->calendar; ?>


  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

<script type="text/javascript">

<?php 
	if($this->calMonth) echo "var calMonth = $this->calMonth;" . PHP_EOL;
	if($this->calYear) echo "var calYear = $this->calYear;" . PHP_EOL;
?>

function showControls () {
	var btns = '<div class="hideFromPrint"><div class="calendar-gui-btn"><button>+</button></div></div>';
	var tds = $('#content table td div').parents('td');
	tds.append(btns).wrapInner('<div style="position:relative;display:block;height:100%;width:100%;">');
	$('#content table button').click(function () {
			location.href= '<?php echo $this->base_url; ?>/training/add/?start-date='+$(this).parents('td').find('.calDay').html()+'/'+calMonth+'/'+calYear;
		});
	return false;
}

$(document).ready( function () {
	// compare dates and style calender
	var tds = $('#content table td div').parent('td');
	tds.each(function () {
		if (!calMonth && !calYear)
			return;

		var me = $(this);
		if(me.find('.calDay').length)
			calDay = me.find('.calDay').html();
		if(calDay && new Date() < new Date(calYear,calMonth-1,calDay))
			me.addClass('trainOld');
		if(calDay && new Date() > new Date(calYear,calMonth-1,calDay))
	 		me.addClass('trainNew');
	});
});

</script>
</div>

</body>
</html>