<?php require_once("views/helpers/DropDown.php"); ?>
<div class="fieldLabel" id="home_address_1_lbl"><?php tp('Address 1');?></div>
	  <div class="fieldInput"><input type="text" name="home_address_1" id="home_address_1" value="<?php echo $this->person['home_address_1'];?>" size="40" maxlength="40"/></div>
	<div class="fieldLabel" id="home_address_2_lbl"><?php tp('Address 2');?></div>
	  <div class="fieldInput"><input type="text" name="home_address_2" id="home_address_2" value="<?php echo $this->person['home_address_2'];?>" size="40" maxlength="40"/></div>

 <div class="fieldLabel" id="home_province_id_lbl"><?php echo (@$this->translation['Region A (Province)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 1, 'home_province_id', @$this->person['home_province_id'], 'home_district_id');?></div>
  <?php if ( $this->setting['display_region_b'] ) { ?>
  <div class="fieldLabel" id="home_district_id_lbl"><?php echo (@$this->translation['Region B (Health District)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 2, 'home_district_id', @$this->person['home_district_id'], ($this->setting['display_region_c']?'home_region_c_id':false));?></div>
  <?php } ?>
  <?php if ( $this->setting['display_region_c'] ) { ?>
  <div class="fieldLabel" id="region_c_id_lbl"><?php echo (@$this->translation['Region C (Local Region)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 3, 'home_region_c_id', @$this->person['home_region_c_id'], false);?></div>
  <?php } ?>
		
	<div class="fieldLabel" id="home_city_lbl"><?php echo (@$this->translation['City or Town']); ?></div><div id="cityAutoComplete">
	    <div class="fieldInput"><input name="home_city" id="home_city" type="text" size="40" maxlength="128" value="<?php echo @$this->person['home_city'];?>" /><input style="margin-left:10px;" type="checkbox" id="is_new_home_city" name="is_new_home_city" value="is_new_home_city" /><label class="label"><?php tp('New city'); ?></label><div class="clear"></div>
	    <div id="cityHomeContainer"  class="autocomplete"></div></div>
	</div>
 <?php renderCityAutocomplete('home','cityHomeContainer',$this->base_url.'/facility/cityList/outputType/text/',$this->setting['num_location_tiers']);?>
	

	<div class="fieldLabel" id="home_postal_code_lbl"><?php tp('Postal code');?></div>
	  <div class="fieldInput"><input type="text" name="home_postal_code" id="home_postal_code" value="<?php echo $this->person['home_postal_code'];?>" size="40" maxlength="40"/></div>