<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

</head>
<body class="yui-skin-sam">


<script language="javascript">
	function gotoPage(objId) {
		var reportSelector = YAHOO.util.Dom.get(objId);
		if ( reportSelector[reportSelector.selectedIndex].value ) {
			window.location = '<?php echo $this->base_url;?>' + reportSelector[reportSelector.selectedIndex].value + '?<?php echo $_SERVER['QUERY_STRING'];?>';
		}
	}
</script>
<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php tp("Report");?></h1>
	<p></p>
    	<?php require_once('peopleReportsPicker.phtml'); ?><br/><br/>
   	<div class="clear"></div>
    	<div class="fieldLabel" id="trainer_lbl"><?php tp('Select trainer report');?></div>
    	<select id="trainer" name="trainer" onchange="gotoPage('trainer');">
    		<option value="">--<?php tp('choose');?>--</option>
    		<option value="/reports/trainers"><?php tp('Trainers by Skill, Language, and PEPFAR');?></option>
   	</select><br/><br/>
   	<div class="clear"></div>
    	<div class="fieldLabel" id="training_lbl"><?php tp('Select training report');?></div>
    	<select id="training" name="training" onchange="gotoPage('training');">
    		<option value="">--<?php tp('choose');?>--</option>
    		<option value="/reports/trainings"><?php tp('Trainings by Name');?></option>
    		<option value="/reports/trainingByParticipants"><?php tp('Trainings by Participant Count');?></option>
   	</select>
  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div>

</body>
</html>