<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?></title>
<?php
require_once('views/helpers/Location.php');
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
$message = '';
$multiple = TRUE; // multi-select for regions
switch ( $this->criteria['cat'] ) {
	case 'pepfar':
		$catagoryLabel = t('PEPFAR');
		$message = t('Unique by').' '.(@$this->translation['PEPFAR Category']).' '.t('and').' '.(@$this->translation['Training Organizer']).'. '.t('Not unique overall.');
		break;
	case 'level':
		$catagoryLabel = (@$this->translation['Training Level']);
		$message = t('Unique by').' '.(@$this->translation['Training Level']).' '.t('and').' '.(@$this->translation['Training Organizer']).'. '.t('Not unique overall.');
		break;
	case 'qualification':
		$catagoryLabel = t('Qualification');
		$message = t('Unique by'.' '.(@$this->translation['Training Organizer']).'. '.t('Not unique overall.'));
		break;
}

?>

</head>
<body class="yui-skin-sam"  >

<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php tp('Participant Reports');?></h1>
	<p></p>
    	<?php require_once('peopleReportsPicker.phtml'); ?>
   <form action="" method="get">
   <fieldset><legend><?php tp('Select Criteria');?></legend>

	<?php region_filters_dropdown($this, $this->locations, $this->criteria, true, false); ?>

	<div class="fieldLabel" id="training_organizer_id_lbl"><?php echo (@$this->translation['Training Organizer']); ?></div>
	<div class="fieldInput"><?php echo $this->organizers_checkboxes; ?><br /></div>

 	<div class="clear"></div>
<div class="fieldLabel"><?php tp('Start date');?></div>
<div class="fieldInput" id="startdate">
    <?php tp("Day");?> <input id="start-day" class="dayfield" type="text" name="start-day" maxlength="2" value="<?php echo $this->criteria['start-day']; ?>"  >
    / <?php tp("Month");?> <input id="start-month" class="monthfield" type="text" name="start-month" maxlength="2" value="<?php echo $this->criteria['start-month']; ?>"  >
    / <?php tp("Year");?> <input id="start-year" class="yearfield" type="text" name="start-year" maxlength="4" value="<?php echo $this->criteria['start-year'];  ?>" >
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	makeCalendar("startdate","start-day", "start-month", "start-year");
		    });
		</script>
	</div>
<div class="fieldLabel"><?php tp('End date');?></div>
<div class="fieldInput" id="enddate">
    <?php tp("Day");?> <input id="end-day" class="dayfield" type="text" name="end-day" maxlength="2" value="<?php echo $this->criteria['end-day']; ?>"  >
    / <?php tp("Month");?> <input id="end-month" class="monthfield" type="text" name="end-month" maxlength="2" value="<?php echo $this->criteria['end-month']; ?>"  >
    / <?php tp("Year");?> <input id="end-year" class="yearfield" type="text" name="end-year" maxlength="4" value="<?php echo $this->criteria['end-year'];  ?>" >
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	makeAdditionalCalendar("enddate","end-day", "end-month", "end-year");
		    });
		</script>
	</div>

  <?php if($message) : ?>
	<div class="fieldLabel" id="training_organizer_id_lbl"></div>
	<div class="fieldInput" style="font-style:italic;"><br><?php echo $message; ?><br /></div>
	<?php endif; ?>


   	<input type="submit" class="submitNoArrow" name="go" value="Preview" />
   </fieldset>
   </form>
 	<div class="hrGrey"></div>
  <?php if ( @$this->results ) { ?>
    <div class="fieldIndentNoMargin"><?php tp('Results');?>  <span class="total"><?php echo $this->count;?> <?php tp('Total Participants by');?> <?php echo $catagoryLabel;?></span><?php echo $this->printAndExport();?></div>

	<div id="quarterTable" class="itechTable"></div><div class="clear"></div><br/>

   <?php } else { ?>
   <div class="fieldIndentNoMargin"><?php tp('Results');?>  <span class="total">0</span></div>
   <?php } ?>
  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div>
<script language="javascript">
YAHOO.util.Event.addListener(window, "load", function() {
	YAHOO.namespace("reports");
    YAHOO.reports.NestedHeaders = new function() {

		    var Data = [
			<?php
				$isFirst = true;
			foreach ($this->results as $statRow) {
				   	if ( !$isFirst ) echo ',';
				   	$rows = array('"'.$statRow['cat'].'"', $statRow['cnt'], $statRow['person_cnt']);
				   	if($this->criteria['training_organizer_option_id']) {
				   	  $rows[] = '"' . htmlspecialchars($statRow['training_organizer_phrase']) . '"';
				   	}
				   	echo '[' . implode(',', $rows) . ']';
				   	$isFirst = false;
			}   ?>];

       var myColumnDefs = [
       		 {key:"cat", label:"<?php tp('Category');?>",sortable:true, resizeable:true},
              {key:"cnt", label:"<?php tp('Participants');?>", sortable:true, resizeable:true},
              {key:"person_cnt", label:"<?php tp('Unique Participants');?>", sortable:true, resizeable:true}
              <?php if($this->criteria['training_organizer_option_id']) { ?>
              , {key:"training_organizer_phrase", label:"<?php echo (@$this->translation['Training Organizer']);?>", sortable:true, resizeable:true}
              <?php } ?>
            ];

        this.myData = new YAHOO.util.DataSource(Data);
        this.myData.responseType = YAHOO.util.DataSource.TYPE_JSARRAY;
        this.myData.responseSchema = {
            fields: ["cat","cnt","person_cnt", "training_organizer_phrase"]
        };

        this.myDataTable = new YAHOO.widget.DataTable("quarterTable", myColumnDefs, this.myData);

	}
} );

</script>
</body>
</html>
