<html>
	<head>
		<title><?php echo $this->escape($this->title);?></title>
		<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">
	<?php
    require_once('views/helpers/ScriptContainer.php');
    print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();      ?>
    
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
						
					});
					$(event.target.parentNode).addClass('row_selected');
					
				});
	 
				/* Add a click handler for the delete row */
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );
	 
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();
				 
				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
		</script>
	</head>
	 <body  class="yui-skin-sam">
     <div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
            <div id="content">
            
			<div id="subcontent">
				<div id="contentheader">
					<h2>People Search</h2><br/>
					<p style="float:left;font-size:13px;">Select criteria</p>
				</div>
				<div class="pad50 clear"></div>
				
				<div class="mainformholder">
                <form name="peoplefind" action="../peoplefind/peoplefind" method="post">
					<label>First name</label>
					<input type="text" name="firstname" value="<?php echo $this->escape($_POST['firstname']);?>">

					<label>Last name</label>
					<input type="text" name="lastname" value="<?php echo $this->escape($_POST['lastname']);?>">


					<label>Cohort</label>
					<select id="cohort" name="cohort">
						<option value="0">Select...</option>
<?php
	foreach ($this->cohort as $cohort){
		echo "<option value=\"" . $cohort['id'] . "\"" . ($_POST['cohort'] == $cohort['id'] ? " selected" : "") . ">" . $cohort['cohortname'] . "</option>\n";
	}
?>
					</select>

					<label>Student cadre</label>
					<select id="cadre" name="cadre">
						<option value="0">Select...</option>
<?php
	foreach ($this->cadre as $cadre){
		echo "<option value=\"" . $cadre['id'] . "\"" . ($_POST['cadre'] == $cadre['id'] ? " selected" : "") . ">" . $cadre['cadrename'] . "</option>\n";
	}
?>
					</select>

					<label>Institution</label>
					<select id="inst" name="inst">
						<option value="0">Select...</option>
<?php
	foreach ($this->institution as $institution){
		echo "<option value=\"" . $institution['id'] . "\"" . ($_POST['inst'] == $institution['id'] ? " selected" : "") . ">" . $institution['institutionname'] . "</option>\n";
	}
?>
					</select>

					<label>Facility</label>
					<select id="fact" name="fact">
						<option value="0">Select...</option>
<?php
	foreach ($this->facility as $facility){
		echo "<option value=\"" . $facility['id'] . "\"" . ($_POST['fact'] == $facility['id'] ? " selected" : "") . ">" . $facility['facility_name'] . "</option>\n";
	}
?>
					</select>

					<label>Return</label>
	                <input type="radio" name="type" value="every" style="margin-left : 30px;"<?php echo $this->escape($_POST['type']) == "every" ? " checked" : "";?>> Everyone
                    <p style="padding : 0px; margin : 0px; background-color : #FFFFFF;">&nbsp;</p>

					<label>&nbsp;</label>
                    <input type="radio" name="type" value="student" style="margin-left : 30px;"<?php echo $this->escape($_POST['type']) == "student" ? " checked" : "";?>> Students
                    <p style="padding : 0px; margin : 0px; background-color : #FFFFFF;">&nbsp;</p>

                    <label>&nbsp;</label>
                    <input type="radio" name="type" value="tutor" style="margin-left : 30px;"<?php echo $this->escape($_POST['type']) == "tutor" ? " checked" : "";?>> Tutor
                    <p style="padding : 0px; margin : 0px; background-color : #FFFFFF;">&nbsp;</p>


					<div class="rightdiv">
						<input type="submit" name="search" class="tsbutton green large" value="Search &raquo;">
					</div>
                    </form>
				</div>
				<div class="pad50 clear"></div>



				<div style="width :100%;">
				<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
					<thead>
						<tr>
							<th>ID</th>
							<th>Name</th>
							<th>Gender</th>
							<th>Institution</th>
							<th>Cohort</th>
						</tr>
					</thead>
					<tbody>
    
    
    
<?php 
	foreach($this->getpeople as $getpeople){
?>
						<tr class="GradeA" style="cursor : pointer;" onClick="window.location.href='<?php echo $getpeople['link']; ?>'">
							<td name="getpeo" style="width : 120px;"><?php echo $getpeople['id']; ?></td>
							<td class=""><?php echo trim ($getpeople['first_name'] . " " . $getpeople['last_name'] . ($_POST['type'] == "every" ? " (" . $getpeople['type'] . ")" : "")); ?></td>
							<td class="" style="width : 150px;"><?php echo $getpeople['gender'] ? $getpeople['gender'] : 'N/A'; ?></td>
							<td class="" style="width : 150px;"><?php echo $getpeople['institutionname'] ? $getpeople['institutionname'] : 'N/A'; ?></td>
							<td class="" style="width : 150px;"><?php echo $getpeople['cohortname'] ? $getpeople['cohortname'] : 'N/A'; ?></td>
						</tr>
<?php
	}
?>
					</tbody>
				</table>
				</div>

				<div>&nbsp;</div>
				<div class="pad20 clear"></div>
				<div class="rightdiv">
					<a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/peopleadd/peopleadd'; ?>" class="tsbutton green large">Add a person &raquo;</a>
				</div>

			</div>
		</div>
        
        </div>
		<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
        </div>

	</body>
</html>