<?php
/*
 * Created on Mar 7, 2008
 *
 *  Built for itechweb
 *  Fuse IQ -- todd@fuseiq.com
 *
 */

$navMain = array( // directory => array of nav items
  'index' => array(
    'index' => t('Home'), // file => label (use "index" for root)
  ));

if ( $this->isLoggedIn() ) {


  if ( $this->hasACL('edit_course')  ){
 	 $navMain['training'] = array(
	    'index' => t('Trainings'),
	    'view'  => t('View/Edit Training'),
	    'add' => t('Add New Training')
	  );
  } else {
	 $navMain['training'] = array(
	    'index' => t('Trainings'),
	    'view'  => t('View Training')
	  );
  }

  if ( $this->hasACL('edit_people')  ){
	  $navMain['person'] = array(
	    'index' => t('People'),
	    'search'  => t('View/Edit Person'),
	    'add' =>  t('Add New Person')
	  );
  } else {
	  $navMain['person'] = array(
	    'index' => t('People'),
	    'search'  => t('View person'),
	  );
  }

  if ( $this->hasACL('edit_course') or $this->hasACL('edit_people') or $this->hasACL('view_people') ) {
     $navMain['facility'] = array(
	  'index' => t('Places')
	);

      if (   $this->hasACL('edit_people')  ) {
      	$navMain['facility']['search']  = t('View/Edit Facility');
      } else if ($this->hasACL('view_people')) {
      	$navMain['facility']['search']  = t('View facility');
      }
      if (   $this->hasACL('edit_people') ) {
      	$navMain['facility']['add']  = t('Add Facility');
      }

      if (   $this->hasACL('edit_course') ) {
     	$navMain['facility']['searchLocation']  = t('View/Edit Training Location');
      } else if ($this->hasACL('view_course')) {
     	$navMain['facility']['searchLocation']  = t('View Training Location');
      }
      if (   $this->hasACL('edit_course')) {
      	$navMain['facility']['addLocation']  = t('Add Training Location');
      }

  }

  if ( $this->hasACL('view_create_reports')) {
	  $navMain['reports'] = array(
	    'index' => t('Reports'),
	    'trainingByParticipants' => t('Training Reports'),
	    'participantsByCategory/cat/pepfar' => t('Participant Reports'),
	    'trainers' => t('Trainer Reports'),
	    'trainingByFacilityCount' => t('Facility Reports'),
	    'needsByPersonName' => t('Assessment Reports'),
	    'roster' => t('Roster Reports'),
	     'data' => t('Data Downloads')
 	  //  'evaluations' => t('Evaluation Reports'),
	  );

  	if ( !$this->setting['display_training_recommend'] ) {
		unset($navMain['reports']['needsByPersonName']);
  	}
  }

   if ( $this->setting['module_evaluation_enabled']) {
	   $navMain['evaluation'] = array(
	      'index' => t('Evaluations')
	   );
   }
   
  $navMain['user'] = array(
    'index' => t('My Account'),
  );

  if ( $this->hasACL('edit_country_options')) {
  	$navMain['user']['../admin/country-settings'] = t('Country Setup');
  	$navMain['user']['../admin/training-settings'] = t('Training Settings');
  	$navMain['user']['../admin/people-settings'] = t('People Settings');
  	$navMain['user']['../admin/facilities-settings'] = t('Facility Settings');
  }
  if ( $this->hasACL('add_edit_users')) {
  	$navMain['user']['add'] = t('Add New User');
  	$navMain['user']['search'] = t('Edit User');
  }
  if ( $this->hasACL('edit_country_options') || $this->hasACL('use_offline_app')) {
   	$navMain['user'][''] = '---------------';
    $navMain['user']['../desktop/create'] = t('Create App Now');
    $navMain['user']['../desktop/download'] = t('Download Application');
  	$navMain['user']['../sync/upload'] = t('Upload Data');
  }
}


$firstName = 'guest';
$loginoutLink =  '<a href="'.(Settings::$COUNTRY_BASE_URL).'/user/login">'.t("login").'</a>';
if ( $this->isLoggedIn() ) $firstName = $this->identity->first_name;
if ( $this->isLoggedIn() ) $loginoutLink = '<a href="'.(Settings::$COUNTRY_BASE_URL).'/user/logout">'.t("logout").'</a>';

// custom inline CSS
if(isset(Settings::$CSS)) {
  echo '<style>' . Settings::$CSS . '</style>';
}

?>


<!-- login links -->
<a href="<?php echo Settings::$COUNTRY_BASE_URL;?>"><img src="<?php
$url_parts = explode('.', $_SERVER['HTTP_HOST']);
$engender = false;
if ( isset($this->setting['logo_id']) ) {
	echo Settings::$COUNTRY_BASE_URL.'/file/download/id/'.$this->setting['logo_id'];
} else if ( @$url_parts[0] == 'eventsmart' OR @$url_parts[1] == 'eventsmart' ) {
     echo Settings::$COUNTRY_BASE_URL.'/images/engenderhealth-logo-v2.gif';
     $engender = true;
} else {
	switch ( strtolower(Settings::$COUNTRY_NAME) ) {
		case 'haiti':
			echo Settings::$COUNTRY_BASE_URL.'/images/haiti_flag.jpg';
			break;
		case 'tanzaniapartners':
			echo Settings::$COUNTRY_BASE_URL.'/images/tanzanian_flag.png';
			break;
		case 'tanzanianacp':
			echo Settings::$COUNTRY_BASE_URL.'/images/tanzanian_flag.png';
			break;
		default:
			echo Settings::$COUNTRY_BASE_URL.'/images/header.gif';
			break;
	}
}

?>" id="headerImg" alt="banner" /></a>
<div style="color:#99CC7E; float:left; padding-top:20px; vertical-align:middle;"><span style="font-size:4em;"><?php echo $this->translation['Application Name'];?></span><br/><span style="margin-left:120px;"><?php echo $this->setting['country'];?></span></div>
<div style="float:right;">
<div id="headerLinks">
<?php print t('Welcome');?>, <?php echo $firstName;?> <span class="pipe">|</span> <?php echo  $loginoutLink;?>&nbsp;

<!-- switch language -->
<div style="margin-top:70px; text-align:right; ">
<?php
if(count($this->languages_enabled) > 1) {
  foreach( $this->languages_enabled as $lang_opt) {
  	$opts []= '<a href="'.Settings::$COUNTRY_BASE_URL.'/index/language?opt='.urlencode($lang_opt).'">'.t($this->languages[$lang_opt]).'</a>';
  }
  print implode ('&nbsp;|&nbsp;', $opts);
}
?>
</div>

</div>

</div><div class="clear"></div>

<!-- main navigation -->
<div id="navMain">
  <?php
  // Detect page
  $parsed_url = parse_url(Settings::$COUNTRY_BASE_URL);
  $pathFront = @$parsed_url['path'];
  if ( $pathFront )
  	$path = str_replace($pathFront,'',$_SERVER['REQUEST_URI']);
  else
  	$path = $_SERVER['REQUEST_URI'];
	// Sean Smith: Added filter out double slashes (handles improper config in globals.php, and other unforseeables)
  $path = str_replace("//",'/',$path);
  $path = str_replace("\\",'/',$path);
  $path = explode('/',$path);

  foreach($navMain as $dir => $navRay) {
    $class = array();
    if($dir == 'index') { $class[] = 'first'; $dir = '';  } // special CSS

    // add "active" class
    if(empty($path[1]) || empty($dir) || $path[1] == $dir) { $class[] = 'active'; }

    echo '
    <div class="flydown" '.($dir == 'user'? 'style="float:right;"':'').' onmouseover="fadeShow(this,\''.$dir.'\');" onmouseout="fadeOut(this,\''.$dir.'\');">
    ';
    echo '<a href="'.Settings::$COUNTRY_BASE_URL.'/'.$dir.'"'.(!empty($class) ? ' class="'.implode(' ', $class).'"' : '').' id="nav'.$dir.'">' . $navRay['index'] . '</a>';

    // Fly-down menu items
    if(count($navRay) > 1) {
      echo '<div class="flydownItems">';
      foreach($navRay as $file => $label) {
        if($file != 'index') {
          echo '<a '.(strlen($file)?'href="'.Settings::$COUNTRY_BASE_URL.'/'.$dir.'/'.$file.'"':'').' >'.$label.'</a>';
        }
      }
		  echo '</div>';
    }

    echo '</div>';

  }

  ?>


</div>

