<?php require_once('views/helpers/DropDown.php'); ?>

<script type="text/javascript">
   <!--//--><![CDATA[//><!--
function updateAge() {
  if ( YAHOO.util.Dom.get( 'birth-year').value > 0 && YAHOO.util.Dom.get( 'birth-month').value > 0 && YAHOO.util.Dom.get( 'birth-day').value > 0) {
    var bday = new Date ( YAHOO.util.Dom.get( 'birth-year').value, YAHOO.util.Dom.get( 'birth-month').value -1, YAHOO.util.Dom.get( 'birth-day').value -1);
    var today = new Date ();
        var age = today.getFullYear() - bday.getFullYear();
        age -= 1;
        bday.setFullYear(today.getFullYear ());
        if ( bday.getMonth() < today.getMonth())
          age += 1;
        else if (bday.getMonth() == today.getMonth() && bday.getDay() < today.getDay())
          age += 1;
    var ageElement =  YAHOO.util.Dom.get( 'age');
    if ( ageElement ) ageElement.value = age;
  }
}

function updateBirthdate() {
  var today = new Date ();
  var age =  YAHOO.util.Dom.get( 'age').value;
  if ( age > 0  )
    YAHOO.util.Dom.get( 'birth-year').value = today.getFullYear() - age;
    YAHOO.util.Dom.get( 'birth-month').value = 1;
    YAHOO.util.Dom.get( 'birth-day').value = 1;
}

YAHOO.util.Event.onDOMReady(updateAge);


// submit form, then redirect
function submitThenRedirect(url) {
	var fld = document.getElementById('redirectUrl');
	fld.value = url;
	document.getElementById('personForm').submit();
//var redirectEl = YAHOO.util.Dom.get('redirectUrl');
//redirectEl.value = url;
//YAHOO.util.Dom.get('personForm').submit();
window.location = url;
}

YAHOO.namespace("example.container");

function init() {

  // Define various event handlers for Dialog
  var handleSubmit = function() {
    //clear error text
    var els = YAHOO.util.Dom.getElementsByClassName('errorText');
    if ( els.length )
      YAHOO.util.Dom.setStyle(els, 'display', 'none');
    this.submit();
  };
  var handleCancel = function() {
    this.cancel();
  };
  var handleSuccess = function(o) {
    var response = o.responseText;
    var responseObj = YAHOO.lang.JSON.parse(response);
    displayStatus(responseObj.status);
    var allGood = true;
    if ( responseObj.messages ) {
      for (var key in responseObj.messages) {
        YAHOO.example.container.addFacility.show();
        displayErrorMessage(key,responseObj.messages[key]);
        allGood = false;
      }
    }

    if ( allGood ) {
      //var facilityEl =  YAHOO.util.Dom.get('facilityInput');
      //var newName = YAHOO.util.Dom.get('facility_name').value;
      //facilityEl.value = newName;
      //alert(YAHOO.util.Dom.get('obj_id').value);
      elProv = YAHOO.util.Dom.get('facility_province_id');
      province_id = elProv.options[elProv.selectedIndex].value;

      elDist = YAHOO.util.Dom.get('facility_district_id');
      district_id = (elDist) ? elDist.options[elDist.selectedIndex].value : "0";
      
      setSelected('person_facility_province_id', province_id);
      filterSubTypeOptions('person_facility_province_id','person_facility_district_id');
      setSelected('person_facility_district_id', district_id);

      <?php if ( $this->setting['display_region_c']) { ?>
      elC = YAHOO.util.Dom.get('facility_region_c_id');
      region_c_id = (elC) ? elC.options[elC.selectedIndex].value : "0";
      filterSubTypeOptions('person_facility_district_id','person_facility_region_c_id');
      setSelected('person_facility_region_c_id', region_c_id);
      <?php } ?>
      
      var newOpt = document.createElement('option');
      newOpt.text = YAHOO.util.Dom.get('facility_name').value;
      newOpt.value = responseObj.obj_id;
      newOpt.selected = true;

      var facSel = document.getElementById('facilityInput');
      try {
        facSel.add(newOpt, null); // standards compliant; doesn't work in IE
      } catch(ex) {
        facSel.add(newOpt); // IE only
      }

    }

  };
  var handleFailure = function(o) {
    alert("<?php tp('Submission failed:');?> " + o.status);
  };

  // Instantiate the Dialog
  YAHOO.example.container.addFacility = new YAHOO.widget.Dialog("addFacility",
              { width : "50em",
                fixedcenter : false,
                visible : false,
                constraintoviewport : true,
                modal : true,
                zIndex: 9100,
                context : ["personForm", "tl", "bl"],
                buttons : [ { text:"Submit", handler:handleSubmit, isDefault:true },
                      { text:"Cancel", handler:handleCancel } ]
              });


  // Validate the entries in the form to require that both first and last name are entered
  YAHOO.example.container.addFacility.validate = function() {
    return true;//do all validation server side
  };

  // Wire up the success and failure handlers
  YAHOO.example.container.addFacility.callback = { success: handleSuccess,
                 failure: handleFailure };

  // Render the Dialog
  YAHOO.example.container.addFacility.render();

  // Show dialog and initialize region selects
  YAHOO.util.Event.addListener("show", "click", YAHOO.example.container.addFacility.show, YAHOO.example.container.addFacility, true);

 }

YAHOO.util.Event.onDOMReady(init);

<?php if($this->mode == 'add') : ?>
var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
  var tredirect = '';
<?php if($this->trainingredirect) { ?>  
  tredirect = "/trainingredirect/<?php echo $this->trainingredirect; ?>";
<?php } ?>
<?php if($this->maketrainer) { ?>
  tredirect = tredirect + "/maketrainer/1";
<?php } ?>
  if ( (sData == null) || (sData.length == 0) )
    sData = '&nbsp;&nbsp;&nbsp;';
    elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/person/edit/id/" + oRecord.getData("id") + tredirect + "' >" + sData + "</a>";
}

var dupeColDefs =
[ {key:"id", label: "ID", sortable:false, resizable:false, formatter: formatViewUrl},
{key:"input", width:15, resizeable:true , label:"", hidden:"true", width:"0", className:"hidden"},
{key:"first_name", width:60, resizeable:true , label:"<?php tp("First Name"); ?>"},
<?php if ( !$this->setting['display_middle_name_last'] ) { ?>
{key:"middle_name", width:66, resizeable:true , label:"<?php echo (@$this->translation['Middle Name']); ?>"},
<?php } ?>
{key:"last_name", width:54, resizeable:true , label:"<?php echo (@$this->translation['Last Name']); ?>"},
{key:"birthdate", width:78, resizeable:true , label:"<?php tp("Date of Birth"); ?>"},
{key:"gender", width:78, resizeable:true , label:"<?php tp("Gender"); ?>"},
{key:"facility_name", width:120, resizeable:true , label:"<?php tp("Facility");?>"},
{key:"national_id", width:80, resizeable:true , label:"<?php echo (@$this->translation['National ID']); ?>"} ];

var dupeDataSource = { } // filled via ajaxDupeSuccess callback

var ajaxDupeSuccess = function(o) {
if(o.responseText !== undefined){
  if(!o.responseText) {
    YAHOO.util.Dom.get('dupecheck').innerHTML = "<em><?php tp('No duplicates found.'); ?></em>";
  } else {
    dupeDataSource = eval(o.responseText);
    makeDynamicDataTable("dupecheck", "<?php tp("If the person already exists, please select their name below."); ?>", dupeDataSource, dupeColDefs);
    YAHOO.util.Dom.removeClass(YAHOO.util.Dom.get('submitAddContinue'), "hidden");
  }
}
}

var ajaxDupeFailure = function(o){
if(o.responseText !== undefined){
  YAHOO.util.Dom.get('dupecheck').innerHTML = o.status + "<br />" + o.statusText;
}
}

var callback = {
success:ajaxDupeSuccess,
failure: ajaxDupeFailure
};

var isTimeout = false;

function buildDupeTable(e) {
if(!isTimeout) {
  last_name = YAHOO.util.Dom.get('last_name').value;
  first_name = YAHOO.util.Dom.get('first_name').value;

  if(last_name || first_name) {
    YAHOO.util.Dom.removeClass(YAHOO.util.Dom.get('duplicateCheckLabel'), "hidden");

    var sUrl = "<?php echo $this->base_url;?>/person/dupeList/outputType/json?";
    sUrl += "last_name=" + last_name + "&";
    sUrl += "first_name=" + first_name + "&";
    var request = YAHOO.util.Connect.asyncRequest('GET', sUrl, callback);

    isTimeout = true;
    setTimeout(function() {
      isTimeout = false;
      if(e) {
        buildDupeTable(false);
      }
    }, 300);
  } else {
    YAHOO.util.Dom.get('dupecheck').innerHTML = "";
  }
}
}

function continueClick() {

// find checked radio
var elChecked = YAHOO.util.Dom.getElementsBy( function(el) {
  return el.checked;
}, 'input',YAHOO.util.Dom.get('dupecheck'));

if(elChecked && elChecked.length) {
  elChecked.form.submit();
} else {
  last_name = YAHOO.util.Dom.get('last_name').value;
  first_name = YAHOO.util.Dom.get('first_name').value;

  if(!last_name || !first_name) {
    alert("<?php tp("Please enter a first and last name."); ?>");
  } else {
    YAHOO.util.Dom.removeClass(YAHOO.util.Dom.get('personAddHide'), "hidden");
    YAHOO.util.Dom.addClass(YAHOO.util.Dom.get('submitAddContinue'), "hidden");
  }
}


return false;
}

YAHOO.util.Event.onDOMReady(function() {
	  YAHOO.util.Event.addListener(YAHOO.util.Dom.get('last_name'), "keyup", buildDupeTable);
	  YAHOO.util.Event.addListener(YAHOO.util.Dom.get('first_name'), "keyup", buildDupeTable);
});

<?php endif; //add only dupe check ?>

YAHOO.util.Event.onDOMReady(function() {
	<?php if ( $this->mode == 'edit' ) { ?>
	addAjaxSubmit('submitPerson','personForm','<?php echo $this->base_url;?>/person/edit/id/<?php echo $this->person['id'];?>/outputType/json');
	<?php } else { ?>
	addAjaxSubmit('submitPerson','personForm','<?php echo $this->base_url;?>/person/add/outputType/json');
	<?php } ?>
	<?php if ( $this->mode == 'edit' ) { ?>
	addAjaxSubmit('submitPersonTop','personForm','<?php echo $this->base_url;?>/person/edit/id/<?php echo $this->person['id'];?>/outputType/json');
	<?php } else { ?>
	//addAjaxSubmit('submitPersonTop','personForm','<?php echo $this->base_url;?>/person/add/outputType/json');
	<?php } ?>
	<?php if ( $this->mode == 'edit' && $this->maketrainer) { ?>
	displayStatus("<?php tp('Please add or verify the trainer information below.'); ?>");
	<?php } ?>
});
//--><!]]>
</script>

<div id="pageHolder">
  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">
<?php if ( $this->mode != 'add' )  { ?>
<div class="actionBtn">
 <button type="button" id="submitPersonTop"><?php tp('Save changes');?></button><br/>
</div>
<?php } ?>
	<?php if ( $this->mode != 'add' ) { ?>
<h1><?php tp('Edit person\'s record');?></h1>
<?php } else { ?>
<h1><?php tp('Add person\'s record');?></h1>
<?php } ?>

<form action="" id="personForm" method="post">
<?php if ( $this->mode != 'add' ) { require_once('history.phtml'); }  ?>

<div class="fieldIndentNoMargin"><?php tp('Personal Information');?></div>

 <?php if ($this->setting['display_people_active']) { ?>
 <div class="fieldLabel"><label for="active"><?php echo (@$this->translation['Is Active']); ?></label></div>
  <div class="fieldInput" style="clear:none;"><input type="checkbox" id="active" name="active" <?php echo ( $this->person['active'] !== 'active' ? '': 'checked="checked"');?> /></div>
 <?php } ?>
<br/>
<?php if ($this->setting['display_people_title']) {
  echo DropDown::render('title_option_id', $this->translation['Title'], $this->titles, 'title_phrase', 'id', $this->person['title_option_id'] );
 } ?>
  <div class="fieldLabel" id="first_name_lbl"><span class="required">*</span><?php echo (@$this->translation['First Name']); ?></div>
  <div class="fieldInput"><input type="text" name="first_name" id="first_name" size="32" maxlength="32" value="<?php echo $this->person['first_name'];?>"/></div><br/>
   <?php if ( $this->setting['display_middle_name'] && !$this->setting['display_middle_name_last'] ) { ?>
  <div class="fieldLabel" id="middle_name_lbl"><?php echo (@$this->translation['Middle Name']); ?></div>
  <div class="fieldInput"><input type="text" name="middle_name" size="32" maxlength="32" value="<?php echo $this->person['middle_name'];?>"/></div>
  <?php }?>
  <div class="fieldLabel" id="last_name_lbl"><span class="required">*</span><?php echo (@$this->translation['Last Name']); ?></div>
  <div class="fieldInput"><input type="text" name="last_name" id="last_name" size="32" maxlength="32" value="<?php echo $this->person['last_name'];?>"/></div>
   <?php if ( $this->setting['display_middle_name'] && $this->setting['display_middle_name_last'] ) { ?>
  <div class="fieldLabel" id="middle_name_lbl"><?php echo (@$this->translation['Middle Name']); ?></div>
  <div class="fieldInput"><input type="text" name="middle_name" size="32" maxlength="32" value="<?php echo $this->person['middle_name'];?>"/></div>
  <?php }?>
 <?php if ($this->setting['display_people_suffix']) {
  echo DropDown::render('suffix_option_id', $this->translation['Suffix'], $this->suffixes, 'suffix_phrase', 'id', $this->person['suffix_option_id'] );
 } ?>
 <?php if ( $this->setting['display_national_id'] ) { ?>
 <div class="fieldLabel" id="national_id_lbl"><?php echo (@$this->translation['National ID']); ?></div>
  <div class="fieldInput"><input type="text" name="national_id" size="32" maxlength="32" value="<?php echo $this->person['national_id'];?>"/></div>
  <?php } ?>
  <?php if ( $this->setting['display_people_file_num'] ) { ?>
 <div class="fieldLabel" id="file_number_lbl"><?php echo (@$this->translation['File Number']); ?></div>
  <div class="fieldInput"><input type="text" name="file_number" size="32" maxlength="64" value="<?php echo $this->person['file_number'];?>"/></div>
  <?php } ?>

<br/>
    <div class="fieldLabel" id="gender_lbl"><span class="required">*</span><?php tp('Gender');?></div><div class="fieldInput">
    <label for="female"><?php tp('Female');?><input type="radio" id="female" name="gender" value="female" <?php echo ( $this->person['gender'] == 'female' ? 'checked="checked"' :'');?> ></input></label>
    <label for="male"><?php tp('Male');?><input type="radio" id="male" name="gender" value="male" <?php echo ( $this->person['gender'] == 'male' ? 'checked="checked"' :'');?>></input></label>
     <label for="na"><?php tp('Unknown');?><input type="radio" id="na" name="gender" value="na" <?php echo ( $this->person['gender'] == 'na' ? 'checked="checked"' :'');?>></input></label></div>
  <div class="clear"></div>
<div class="fieldLabel"><?php tp('Birth date');?></div>
    <div class="fieldInput">
                <?php tp('Day');?> <input id="birth-day" onchange="updateAge()" class="dayfield" type="text" value="<?php echo $this->person['birthdate-day'];?>" name="birth-day" />
                / <?php tp('Month');?> <input id="birth-month" onchange="updateAge()" class="monthfield" type="text" value="<?php echo $this->person['birthdate-month'];?>" name="birth-month" />
                / <?php tp('Year');?> <input id="birth-year" onchange="updateAge()" class="yearfield" type="text" value="<?php echo $this->person['birthdate-year'];?>" name="birth-year" />
</div>
<?php if ( $this->setting['display_people_age'] ) : ?>
  <div class="clear"></div>
  <div class="fieldLabel"><?php tp('Age');?></div>
  <input type="text" class="fieldInput" id="age" style="width:40px;" onchange="updateBirthdate();"></input>
<?php endif; //age ?>

<?php if($this->mode == 'add') { ?>

  <div class="clear"></div>
  <div class="fieldIndentNoMargin hidden" id="duplicateCheckLabel"><?php tp('Duplicate Check');?></div>
  <div id="dupecheck"></div>
  <input type="submit" id="submitAddContinue" class="submitArrow" value="<?php tp('Continue');?>" onclick="return continueClick();" />
  <div class="clear"></div>
  <div id="personAddHide" class="hidden" >
<?php } ?>
	  <div class="clear"></div>
	  <div class="hrGrey"></div>
	  <div class="clear"></div>

	<?php require_once('edit-body-addtl.phtml'); ?>
	<?php require_once('edit-body-rec.phtml');?>
	<?php if($this->mode == 'edit') require_once('edit-body-class-history.phtml');?>


	<?php if($this->trainingredirect) : ?>
			  <input type="hidden" name="trainingredirect" value="<?php echo $this->trainingredirect; ?>">
			<?php endif; ?>
			<?php if($this->maketrainer) : ?>
			  <input type="hidden" name="maketrainer" value="<?php echo $this->maketrainer; ?>">
			<?php endif; ?>
			<?php if($this->days) : ?>
			  <input type="hidden" name="days" value="<?php echo $this->days; ?>">
	<?php endif; ?>
	 <div class="clear"></div>
	<br/>

	<?php if($this->mode == 'edit' && $this->setting['display_external_classes']) require_once('edit-body-exclass-history.phtml'); ?>
	
	<?php if($this->mode == 'edit') require_once('edit-body-history-table.phtml');?>
<div class="clear"></div>
<div class="actionBtn">
<button type="button" id="submitPerson"><?php tp('Save changes');?></button><br />
</div>

<?php if($this->mode == 'add')
  echo '</div>'; //personAddHide
?>

<input type="hidden" name="redirectUrl" id="redirectUrl" value="" />

</form>
<div class="clear"></div>
</div> <!-- content -->

<div id="addFacility" >
<div class="hd"><?php tp('Add New Facility');?></div>
<div class="bd">
<h1><?php tp('Please enter facility information');?></h1>
<form action="<?php echo $this->base_url;?>/facility/add/outputType/json" method="post">
<?php require_once('views/scripts/facility/addfacility-form.phtml');?>

</form>
</div> <!-- bd -->
<div class="clear"></div>
</div> <!--  addFacility -->

<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div> <!--  page holder -->
