<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php tp('Edit Account');?></title>
		<?php
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();
		?>

		<script language="javascript">
			function setOrgAccessStatus() {
				var edCourseRB = YAHOO.util.Dom.get("edit_course");
				var orgFields = YAHOO.util.Dom.get("orgs").getElementsByTagName('input');
				for(var i = 0; i < orgFields.length; i++) {
					var isDisabled = false;
					if (edCourseRB.checked == false) isDisabled = true;
					orgFields[i].disabled = isDisabled;
				}
				var allOrgsRB = YAHOO.util.Dom.get("training_organizer_option_all");
				if ( allOrgsRB.checked &&  edCourseRB.checked ) {
					for(var i = 0; i < orgFields.length; i++) {
						orgFields[i].checked = true;
						orgFields[i].disabled = true;
					}

					allOrgsRB.disabled = false;
				} else if ( edCourseRB.checked ) {
					for(var i = 0; i < orgFields.length; i++) {
						orgFields[i].disabled = false;
					}
				}
			}
			YAHOO.util.Event.onDOMReady(setOrgAccessStatus);

		</script></head>
		<body class="yui-skin-sam">

			<div id="pageHolder">

				<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
				<div id="content">
					<h1><?php tp('Edit Account');?></h1>
					<div class="clear"></div>
					<form action="" id="userForm" method="post">
						<div class="fieldLabel" id="first_name_lbl"><span class="required">*</span><?php echo $this->translation['First Name'];?></div>
						<div class="fieldInput"><input type="text" name="first_name" size="32" maxlength="32" value="<?php echo $this->user['first_name'];?>"/></div>
						<div class="fieldLabel" id="last_name_lbl"><span class="required">*</span><?php echo $this->translation['Last Name'];?></div>
						<div class="fieldInput"><input type="text" name="last_name" size="32" maxlength="32" value="<?php echo $this->user['last_name'];?>"/></div>
						<div class="fieldLabel"  id="username_lbl"><span class="required">*</span><?php tp('Login');?></div>
						<div class="fieldInput"><input type="text" name="username" size="32" maxlength="32" value="<?php echo $this->user['username'];?>"/></div>
						<div class="fieldLabel"  id="email_lbl"><span class="required">*</span><?php tp('E-mail');?></div>
						<div class="fieldInput"><input type="text" name="email" size="32" maxlength="255" value="<?php echo $this->user['email'];?>"/></div>
						<div class="fieldLabel"  id="password_lbl"><?php tp('New password');?></div>
						<div class="fieldInput"><input type="password" name="password" size="32" maxlength="32" autocomplete="false" autocomplete='off' value=""/></div>
						<div class="fieldLabel"  id="confirm_password_lbl"><?php tp('Confirm new password');?></div>
						<div class="fieldInput"><input type="password" name="confirm_password" size="32" maxlength="32" autocomplete='off' value=""/></div>
						<div class="clear"></div>
						<fieldset ><legend><?php tp('Access Level');?></legend>
							<div class="fieldLabel" ><?php tp('Trainings');?></div>
							<div class="fieldInput">
								<div class="float50"><label for="edit_course"><input type="radio" id="edit_course" name="edit_course" value="edit_course" <?php if ( array_search('edit_course',$this->user['acls']) !== false ) echo 'CHECKED'; ?>  onchange="setOrgAccessStatus();" ><?php tp('Add/Edit/Delete');?></input></label></div>
								<label for="view_course"><input type="radio" id="view_course" name="edit_course" value="view_course"  <?php if ( array_search('view_course',$this->user['acls']) !== false ) echo 'CHECKED'; ?>  onchange="setOrgAccessStatus();" ></input><?php tp('View only');?></label>
							</div>
							<div class="fieldLabel"><?php tp('People');?></div>
							<div class="fieldInput">
							<div class="float50"><label for="edit_people"><input type="radio" id="edit_people" name="edit_people" value="edit_people" <?php if ( array_search('edit_people',$this->user['acls']) !== false ) echo 'CHECKED'; ?> ><?php tp('Add/Edit/Delete');?></input></label></div>
							<label for="view_people"><input type="radio" id="view_people" name="edit_people" value="view_people" <?php if ( array_search('view_people',$this->user['acls']) !== false ) echo 'CHECKED'; ?> ></input><?php tp('View only');?></label>
							</div>

							<div class="fieldLabel">Reports</div><div class="fieldInput"><div class="float50"><input type="checkbox" id="view_create_reports" name="view_create_reports" <?php if ( array_search('view_create_reports',$this->user['acls']) !== false ) echo 'CHECKED'; ?> /><label for="view_create_reports"><?php tp('View/create reports');?></label></div></div>
						<div><div class="fieldLabel">Admin</div><div class="fieldInput">
							<div class="float50">
								<input type="checkbox" id="edit_country_options" name="edit_country_options"  <?php if ( array_search('edit_country_options',$this->user['acls']) !== false ) echo 'CHECKED'; ?> /><label for="edit_country_options"><?php tp('Edit country options')?></label>
								<br>
								<input type="checkbox" name="training_title_option_all" id="training_title_option_all" value="training_title_option_all"  <?php if ( array_search('training_title_option_all',$this->user['acls']) !== false ) echo 'CHECKED'; ?> onchange="setOrgAccessStatus();" /><label for="training_title_option_all"><?php tp('Add Training Titles');?></label>
								<br>
								<input type="checkbox" id="use_offline_app" name="use_offline_app" value="use_offline_app" <?php if ( array_search('use_offline_app',$this->user['acls']) !== false ) echo 'CHECKED'; ?> /><label for="use_offline_application"><?php tp('Use Offline Application')?></label>
							</div>
							<input type="checkbox" id="add_edit_users" name="add_edit_users"   <?php if ( array_search('add_edit_users',$this->user['acls']) !== false ) echo 'CHECKED'; ?> ><label for="add_edit_users"><?php tp('Add/Edit users');?></label>
						</div></div>
						<div><div class="fieldLabel"><?php tp('Approval');?></div><div class="fieldInput"><div class="float50"><input type="checkbox" id="approve_trainings" name="approve_trainings" <?php if ( array_search('approve_trainings',$this->user['acls']) !== false ) echo 'CHECKED'; ?>/><label for="approve_trainings"><?php tp('Approve trainings');?></label></div></div></div>
						<div><div class="fieldLabel"><?php tp('Files');?></div><div class="fieldInput"><div class="float50"><input type="checkbox" id="admin_files" name="admin_files" <?php if ( array_search('admin_files',$this->user['acls']) !== false ) echo 'CHECKED'; ?>/><label for="admin_files"><?php tp('Upload and delete');?></label></div></div></div>
						<div><div class="fieldLabel"></div><div class="fieldInput"><div class="float50"><input type="checkbox" name="pre_service" id="pre_service" value="pre_service" <?php if ( array_search('pre_service',$this->user['acls']) !== false ) echo 'CHECKED'; ?> /><label for="pre_service">Pre-service access</label></div></div>

					</fieldset>
					<fieldset id="orgs" ><legend><?php tp('Organizer access');?></legend>
						<div><div class="fieldLabel"></div><div class="fieldInput"><div class="float50"><input type="checkbox" name="training_organizer_option_all" id="training_organizer_option_all" value="training_organizer_option_all"  <?php if ( array_search('training_organizer_option_all',$this->user['acls']) !== false ) echo 'CHECKED'; ?> onchange="setOrgAccessStatus();" /><label for="training_organizer_all"><?php tp('All Training Organizers');?></label></div></div>
							<?php
							foreach( $this->training_organizer as $org ) {
								echo '<div><div class="fieldLabel"></div><div class="fieldInput"><div class="float50"><input type="checkbox" name="training_organizer_option_id[]" id="training_organizer_option_'.$org['id'].'" value="'.$org['id'].'" '.(@$org['user_id']? 'CHECKED':'').' /><label for="$training_organizer_'.$org['id'].'">'.$org['training_organizer_phrase'].'</label></div></div>';
							}
							?>

						</fieldset>
						<?php if ( !$this->user['is_blocked'] ) { ?>
						<div style="margin-left:2em;"><a href="" onclick="doDelete(); return false;"><?php tp('Block this User');?></a></div>
						<script language="JavaScript">
							function doDelete() {
								if(confirm("<?php tp('Are you sure you wish to block this user?');?>")) {
									window.location = '<?php echo $this->base_url;?>/user/delete/id/<?php echo $this->user['id'];?>';
									return false;
								}
							}
						</script>
						<?php } else { ?>
						<div style="margin-left:2em;">This user is currently blocked. <a href="" onclick="doActivate(); return false;"><?php tp('Activate this User');?></a></div>
						<script language="JavaScript">
							function doActivate() {
								if(confirm("<?php tp('Are you sure you wish to activate this user?');?>")) {
									window.location = '<?php echo $this->base_url;?>/user/activate/id/<?php echo $this->user['id'];?>';
									return false;
								}
							}
						</script>
						<?php } ?>
						<button type="button" id="Finished" title="save this record" class="submitNoArrow" /><?php tp('Save changes');?></button>
						<div class="clear"></div>


					</form>
					<div class="clear"></div>
					<script type="text/javascript">
						addAjaxSubmit('Finished','userForm','<?php echo $this->base_url;?>/user/edit/id/<?php echo $this->user['id'];?>/outputType/json');
					</script>

				</div>
				<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


			</div>

		</body>
	</html>