<html>
	<head>
		<title><?php echo $this->escape($this->title);?></title>
		<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">

	<?php
    require_once('views/helpers/ScriptContainer.php');
    print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();      ?>
    
<script type="text/javascript" src="<?php  echo Settings::$COUNTRY_BASE_URL.'/js/scripts/jquery-1.7.1.min.js'; ?>"></script>
<script type="text/javascript" src="<?php  echo Settings::$COUNTRY_BASE_URL.'/js/scripts/jquery-ui-1.8.17.custom.min.js'; ?>"></script>
<script type="text/javascript" language="javascript" src="<?php  echo Settings::$COUNTRY_BASE_URL.'/js/scripts/jquery.dataTables.js'; ?>"></script>
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true
				});
				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});
	 
				/* Add a click handler for the delete row */
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );
	 
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();
				 
				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
		</script>
	</head>
	<body>
     <div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
            <div id="content">
			<div id="subcontent">
				<div id="contentheader">
					<h2>Cohort Search</h2><br>
			
				</div>
				<div class="pad50 clear"></div>
				<form  action="<?php echo $this->escape($this->action);?>" id="peopleadd" method="post">
				<div class="mainformholder">
                    
               <p style="padding-left:105px;font-weight:bold;">Select Criteria</p><br>
					<label>Cohort Name</label>
					<input type="text" name="cohortname" size="32" maxlength="32">
					
					<label>Cohort ID</label>
					<input type="text" name="cohortid" size="32" maxlength="32">
						
 					<label>Cohort Start Date</label>
					<input type="text" name="startdate" size="32"  class="calendarbox">

					<label>Cohort Gruduation Date</label>
					<input type="text" name="graddate" size="32" maxlength="32" class="calendarbox">

					<label>Institution</label>
					<input type="text" name="institution" size="32" maxlength="32">
                    
                    <label>Cadre</label>
					<input type="text" name="cadre" size="32" maxlength="32">


					
         <div class="rightdiv" style="margin:20px 0 0 -50px;">
		<input type="submit" name="update" value="Search &raquo;" class="tsbutton green large">	</div>
        
					</div></form>
                    
					
<?php /*?><div style="width :900px;">
<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:900px">
	<thead>
		<tr>
			<th>ID</th>
			<th>Start Date</th>
			<th>End Date</th>
			<th>Institution</th>
            <th># of members</th>
			<th>Cohort</th>
		</tr>
	</thead>
	<tbody>
    	
         <?php foreach ($this->getcohort as $fetchcohort){ ?>
		<tr class="GradeA">
			<td><?php echo $fetchcohort[id]; ?></td>
			<td class=""><?php echo $fetchcohort[startdate]; ?></td>
			<td class=""><?php echo $fetchcohort[graddate]; ?></td>
			<td class="">Institution</td>
            <td class="">members</td>
			<td class="">Cohort</td>
		</tr>
		<?php } ?> 
	</tbody>
</table>
</div>
                
           <a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/cohort/cohortadd'; ?>" style="float:left;font-size:14px;margin-top:-150px;" class="tsbutton green large">Add New Cohort</a><?php */?>     
				</div>
            </div>
		</div>
       			

		<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
        </div>
	</body>
</html>