<?php 
require_once('views/helpers/Location.php');
$filters = '';
ob_start();
if ( $this->tier > 1) {
  print '<label>Filter by '.@$this->translation['Region A (Province)'].'</label>'; 
  renderFilter($this->locations, 1, 'province_id', $this->province_id, 'district_id');
  print '<br/>';
}
if ( $this->tier > 2)  {
  print '<label>Filter by  '.@$this->translation['Region B (Health District)'].'</label>'; 
  renderFilter($this->locations, 2, 'district_id', $this->district_id, false);

}
$filters = ob_get_contents(); ob_end_clean();

$formPrefix = '
<script type="text/javascript">
<!--//--><![CDATA[//><!--

YAHOO.util.Event.onDOMReady(function () {
  function change_tier(e, obj) { 
      window.location=\''.($this->base_url).'/admin/country-region/tier/\' + obj.value + \'/location/'.($this->location_id).'\';
  }
  function change_location(e, obj) { 
      window.location=\''.($this->base_url).'/admin/country-region/tier/'.($this->tier).'/location/\' + obj.value;
  }
  
  YAHOO.util.Event.addListener(YAHOO.util.Dom.get("province_id"), "change", change_location, YAHOO.util.Dom.get("province_id"));
  YAHOO.util.Event.addListener(YAHOO.util.Dom.get("district_id"), "change", change_location, YAHOO.util.Dom.get("district_id"));
  YAHOO.util.Event.addListener(YAHOO.util.Dom.get("t1"), "click", change_tier,YAHOO.util.Dom.get("t1"));
  YAHOO.util.Event.addListener(YAHOO.util.Dom.get("t2"), "click", change_tier,YAHOO.util.Dom.get("t2"));
  YAHOO.util.Event.addListener(YAHOO.util.Dom.get("t3"), "click", change_tier,YAHOO.util.Dom.get("t3"));
     
});


//--><!]]> 
</script>

Enter locations for this country or import a CSV file.<br/><br/>
<input type="file" name="import" /> <input type="submit" value="Import" />
<hr/>
Select the Region below to add values<br/><ul>';
for($i = 1; $i < $this->setting['num_location_tiers']; $i++) {
	if ( $i == 1) $formPrefix .= "<li><input type='radio' id='t1' name='tier' value='1' ".($this->tier == 1?"checked='checked'":"")." /><label>".$this->translation['Region A (Province)']."</label></li>";
  if ( $i == 2) $formPrefix .= "<li><input type='radio' id='t2' name='tier' value='2' ".($this->tier == 2?"checked='checked'":"")." /><label>".$this->translation['Region B (Health District)']."</label></li>";
  if ( $i == 3) $formPrefix .= "<li><input type='radio' id='t3' name='tier' value='3' ".($this->tier == 3?"checked='checked'":"")." /><label>".$this->translation['Region C (Local Region)']."</label></li>";
}
$formPrefix .= '</ul>
<br/>
'.$filters;
require '_template_edittable.phtml'; 

?>